# This file is never read -- it's just a copy of the pipeline's
# configuration in the Buildkite UI.

steps:
  - name: ":pipeline:"
    command: |
      PATH=/bin:/usr/bin
      treesha="$$(git ls-tree -d HEAD .buildkite | awk '{print $$3}')"
      if [ -z "$${treesha}" ]; then echo "No SHA for .buildkite/"; exit 0; fi
      if [ "$${#treesha}" -lt 40 ]; then echo "Short SHA for .buildkite/"; exit 1; fi
      echo ".buildkite tree is $${treesha}"
      if curl "https://gist.githubusercontent.com/matthewd/3f98bcc9957c8ddf2204a390bf3a6cdd/raw/list" | grep -a -F -x "$${treesha}"; then
        echo "Known tree; generating pipeline"
        .buildkite/pipeline-generate | buildkite-agent pipeline upload
      else
        echo "Unknown tree; requesting approval"
        buildkite-agent pipeline upload .buildkite/approval-request.yml
      fi
